# Create table for optimization of transactions
CREATE TABLE TABLE_LATEST_UPDATES AS
# Create CTE data from table with previous update values
WITH TABLES_UPDATES_CTE
AS
(SELECT *, Lag(UPDATE_TIMESTAMP) OVER(
       ORDER BY FULL_TABLE_NAME, MEASUREMENT_TIMESTAMP) 
       AS PREVIOUS_UPDATE,
          Lag(FULL_TABLE_NAME) OVER(
       ORDER BY FULL_TABLE_NAME, MEASUREMENT_TIMESTAMP) 
       AS PREVIOUS_FULL_TABLE_NAME FROM TABLES_UPDATES
       ORDER BY FULL_TABLE_NAME, MEASUREMENT_TIMESTAMP)
SELECT DISTINCT ACCOUNT, FULL_TABLE_NAME, PREVIOUS_UPDATE, UPDATE_TIMESTAMP, 
TIMESTAMPDIFF(SECOND, PREVIOUS_UPDATE, UPDATE_TIMESTAMP) AS CN_UPDATE_DIFF
FROM TABLES_UPDATES_CTE
WHERE FULL_TABLE_NAME = PREVIOUS_FULL_TABLE_NAME AND PREVIOUS_UPDATE != UPDATE_TIMESTAMP